name: DDD banking example Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build with Maven
        working-directory: "./1 Hands-on Legacy Code"
        run: ./mvnw --batch-mode --update-snapshots verify
